services:
  prismo-app:
    # Upload from dockerhub, uncomment this
    #image: prismo-app
    # Build locally, uncomment this
    build: .
    environment:
      HOST_HOSTNAME: $HOST_HOSTNAME
    container_name: prismo-app
    restart: always
    ports:
      - 80:5000
    privileged: true
    volumes:
      - "./data/:/app/external/"
      - /run/udev:/run/udev:ro
    devices:
      # Here is some stuff to translate USB device to container.
      - /dev/ttyUSB0:/dev/ttyUSB0:rw
    device_cgroup_rules:
      # https://stackoverflow.com/a/62758958/2514290
      - "c 188:* rmw"
      - "c 166:* rmw"
      - "c 4:* rmw"
    group_add:
      - dialout
