GET http://localhost:5000/reader/name1/accesses


###
POST http://127.0.0.1:5000/reader/test_slack_device/log_operation
Content-Type: application/json

{
  "operation": "lock",
  "data": {
    "key": "my_slack_key"
  }
}

###
POST http://127.0.0.1:5000/reader/test_slack_device/log_operation
Content-Type: application/json

{
  "operation": "unlock",
  "data": {
    "key": "my_slack_key"
  }
}
