GET http://localhost:5000/reader/name1/accesses


###
POST http://127.0.0.1:5000/reader/device1/log_operation
Content-Type: application/json

{
  "operation": "lock",
  "data": {
    "key": "user_key_1"
  }
}
