#!/usr/bin/env lua

print("Content-type: application/json")
print("")

local ip = os.getenv("REMOTE_HOST")
local first = true

io.write('{"ip": "', ip, '", "macs": [')
for line in io.lines('/proc/net/arp') do
  fields = {}
  line:gsub("([^ ]*)".." ", function(c)
    if c ~= "" then
      table.insert(fields, c)
    end
  end)
  if fields[1] == ip then
    if first then
      first = false
    else
      io.write(", ")
    end
    io.write('"', fields[4], '"')
  end
end
io.write("]}")
